name: Boilerplate-CI

on: [push]

jobs:  
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ucreate
          POSTGRES_DB: nodejs_boilerplate_test
        ports:
        - 5436:5432

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Check rejected commits
      env:
        REVIEWEE_URL: https://api.reviewee.it
        COMMITS_CHECK_ENDPOINT: repository/roche_ventana-api/haveRejectedCommits
        COMMITS_CHECK_INDICATOR: \"success\":true
      run: wget ${REVIEWEE_URL}/${COMMITS_CHECK_ENDPOINT} -q -O - | grep -q  ${COMMITS_CHECK_INDICATOR}
      
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present        
      env:
        CI: true
    - name: Lint Code Base
      uses: docker://github/super-linter:v2.2.0
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_ANSIBLE: false    

    - name: Check code quality
      run: npm run lint
       
    - name: Slack notification
      if: success()
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}
        MESSAGE: Build succeed
        USERNAME: ucreate
        CHANNEL: general
      uses: svikramjeet/git-actions@master
    - name: Slack notification
      if: failure()
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}
        MESSAGE: Build failure
        USERNAME: ucreate
        CHANNEL: general
      uses: svikramjeet/git-actions@master  

